### ISSUE TITLE
Clashes with chruby

### ISSUE THREAD

**Issue by radavis** [vikram7/rubies#29]
This is a bummer:

```
$ which rubies
rubies: aliased to chruby
```

Looking into a fix.

**Comment by radavis** [comment]
Figured out this was due to the ohmyzsh chruby plugin.

**Comment by radavis** [comment]
Either remove the `chruby` plugin from your `.zshrc` file, or comment out the following line in `~/.oh-my-zsh/plugins/chruby/chruby.plugin.zsh`

```
alias rubies="chruby"
```

**Comment by vikram7** [comment]
Thanks @radavis !
